DROP DATABASE IF EXISTS db_name;
DROP USER IF EXISTS `db_user`@`%`;
CREATE DATABASE IF NOT EXISTS db_name CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `db_user`@`%` IDENTIFIED WITH mysql_native_password BY 'db_password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `db_name`.* TO `db_user`@`%`;