spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${DB_URL}
spring.jpa.database=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

spring.datasource.hikari.pool-name=${DB_POOL_NAME}
spring.datasource.hikari.maximum-pool-size=${DB_POOL_MAX_SIZE}
spring.datasource.hikari.data-source-properties.cachePrepStmts=${DB_CACHE_PREP_STMTS}
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=${DB_PREP_STMT_CACHE_SIZE}
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=${DB_PREP_STMT_CACHE_SQL_LIMIT}
spring.datasource.hikari.data-source-properties.useServerPrepStmts=${DB_USE_SERVER_PREP_STMTS}
spring.datasource.hikari.data-source-properties.useLocalSessionState=${DB_USE_LOCAL_SESSION_STATE}
spring.datasource.hikari.data-source-properties.rewriteBatchedStatements=${DB_REWRITE_BATCHED_STATEMENTS}
spring.datasource.hikari.data-source-properties.cacheResultSetMetadata=${DB_CACHE_RESULT_SET_METADATA}
spring.datasource.hikari.data-source-properties.cacheServerConfiguration=${DB_CACHE_SERVER_CONFIGURATION}
spring.datasource.hikari.data-source-properties.elideSetAutoCommits=${DB_ELIDGE_SET_AUTO_COMMITS}
spring.datasource.hikari.data-source-properties.maintainTimeStats=${DB_MAINTAIN_TIME_STATS}

#Show SQL logging
#spring.jpa.properties.hibernate.show_sql=true

#Format SQL
#spring.jpa.properties.hibernate.format_sql=true

#Show bind values
#logging.level.org.hibernate.orm.jdbc.bind=trace