spring.application.name=book-exchange
spring.h2.console.enabled=true
logging.level.com.example=debug
spring.flyway.enabled=false
spring.docker.compose.enabled=false

app.base-url=${APP_BASE_URL:http://localhost:8080}
app.jwt-secret-key=${APP_JWT_SECRET_KEY}
app.email-sent-from=${APP_EMAIL_SENT_FROM}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT:2525}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.messages.basename=i18n/messages_user,i18n/messages_admin,i18n/messages_field,i18n/messages_system
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true
spring.messages.use-code-as-default-message=true

#logging.level.org.springframework.context.support.ResourceBundleMessageSource=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.filter=TRACE

#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=drop-and-create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-source=metadata
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=drop-and-create.sql
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=drop-and-create.sql